import { useMemo, useId as useReactId } from 'react';

export function useId(id?: string) {
	const autogeneratedId = useReactId();
	return useMemo(() => id ?? autogeneratedId, [autogeneratedId, id]);
}
